// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArG-G0GiU39k5TT2Z91KVTJRzYDklvx3A',
    appId: '1:666438687646:web:b35e9310b19dfc0d66148f',
    messagingSenderId: '666438687646',
    projectId: 'futbolapp-1d746',
    authDomain: 'futbolapp-1d746.firebaseapp.com',
    storageBucket: 'futbolapp-1d746.firebasestorage.app',
    measurementId: 'G-LE576Q9KR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbek14RhXk8XSqHQFyRNVq3TKTfNl45k',
    appId: '1:666438687646:android:715a3b7d40967e8166148f',
    messagingSenderId: '666438687646',
    projectId: 'futbolapp-1d746',
    storageBucket: 'futbolapp-1d746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBKtQhzYxsWpUcaZv9jkKy098f6kROEXk',
    appId: '1:666438687646:ios:6c29d46c3cb7191866148f',
    messagingSenderId: '666438687646',
    projectId: 'futbolapp-1d746',
    storageBucket: 'futbolapp-1d746.firebasestorage.app',
    iosBundleId: 'com.example.futbolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBKtQhzYxsWpUcaZv9jkKy098f6kROEXk',
    appId: '1:666438687646:ios:6c29d46c3cb7191866148f',
    messagingSenderId: '666438687646',
    projectId: 'futbolapp-1d746',
    storageBucket: 'futbolapp-1d746.firebasestorage.app',
    iosBundleId: 'com.example.futbolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArG-G0GiU39k5TT2Z91KVTJRzYDklvx3A',
    appId: '1:666438687646:web:d47e97680c58242e66148f',
    messagingSenderId: '666438687646',
    projectId: 'futbolapp-1d746',
    authDomain: 'futbolapp-1d746.firebaseapp.com',
    storageBucket: 'futbolapp-1d746.firebasestorage.app',
    measurementId: 'G-1M7TDRJ52V',
  );
}
